
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/heima?useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.seckill.entity