server:
  port: 0


spring:
  rabbitmq:
    host: 39.99.225.61 # 主机名
    port: 5672 # 端口
    virtual-host: /bot # 虚拟主机
    username: twip # 用户名
    password: 82991400 # 密码
    cache:
      channel:
        checkout-timeout: 3000000
    template:
      receive-timeout: 3000000
    listener:
      simple:
        prefetch: 1
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.qq.com
    #服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: 2429203557@qq.com
    #授权码
    password: grceopdwrqrhdjdi
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#  servlet:
#    multipart:
#      max-file-size: 3MB
#      max-request-size: 10MB